Revert "Removed lint support as it breaks the build on travis (ImportError: cannot import name wraps)."
This reverts commit b6665feab0c6759f215b6781633d9286b08daeec.